### PR TITLE
Adjust compact coil recipes for balance.

### PR DESCRIPTION
**Pull request by GTNH-Colen**
- Make coil costs ~80% of what they would be if you made 64 reactors.
- Fix MK5 shenanigans (again)
- Add disassembly recipes for compact coils.

### CODE REVIEW

**Comment by GTNH-Colen** [comment]
Change to usage of 3 coils per compact is intended, reasoning is as follows:

558 coils used in a compact mega fusion which gives 64 parallel, if each compact coil costs 3 regular coils then that's 3*558=1674 coils. 64 Fusions would actually take 2048 coils so 1674/2048 = 81.7% or a 18% saving. I think that is fair and balanced. You also save 25% of the computer costs don't forget given it only needs 48 per mega. You save casings as well, which for something like the MK4 defo gets costly. AND energy hatches... 

I got rid of the recursive recipe because it was a nightmare to try balance properly, this method is much more consistent and still enables further upgrading if they desire.

**Comment by GlodBlock** [comment]
then why the disassemble only gives 1 coil back?

**Comment by GTNH-Colen** [comment]
> then why the disassemble only gives 1 coil back?

It's 1:1, so fully recycles.

**Comment by GlodBlock** [comment]
isn't that 3:1?

**Comment by GTNH-Colen** [comment]
> isn't that 3:1? you lost 2 coils when recycle the old one

Ahhh I see your point, it's 6am for me lol. Will fix that.

**Review by Dream-Master — APPROVED** [review]

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
