### PR TITLE
Coolant Tower: pull steam from all available hatches.

### PR DESCRIPTION
**Pull request by fluffle**
Also reduce recipe time to 1s because 5s of steam from an XL turbine is A LOT.

Fixes: GTNewHorizons/GT-New-Horizons-Modpack#12104.

### CODE REVIEW

**Comment by boubou19** [comment]
Do you have asked other devs about steam reduction?

**Comment by fluffle** [comment]
Please consider this me asking in the form of a PR -- I'm happy to make any changes you want. I can appear on the GTNH discord if you really want me to but i'm a bit lazy, I grew up on IRC in the 90s and haven't really bothered with web 2.0 remakes.

**Comment by Steelux8** [comment]
I definitely think this needs more discussion, since most devs didn't even know about the Coolant Tower in detail. First off, why is this multi necessary when the intention is to chain the turbines from supercritical to superheated to normal steam? It's the same as the process from EV, whether or not SH steam only has 1/100 of the EU of SC.

**Comment by King65868** [comment]
> I definitely think this needs more discussion, since most devs didn't even know about the Coolant Tower in detail. First off, why is this multi necessary when the intention is to chain the turbines from supercritical to superheated to normal steam? It's the same as the process from EV, whether or not SH steam only has 1/100 of the EU of SC.

SC steam outputs regular steam, not SH steam. Also SH steam has 1/50 the EU of SC steam, it’s 1/100 of regular steam.

**Comment by fluffle** [comment]
Personally, I have no interest in building a normal XL steam turbine that would produce a tiny fraction of the power generated by the XL SC turbine, simply because I want to turn the steam back into distilled water to close the loop on my power generation setup. The cooling tower provides a reasonable-looking, cheap, and thematically accurate way of condensing steam such that I can do this.

My current setup is 2xT3 fusion making tin plasma -> extreme HX -> XL SC turbine w/ 16 cosmic neutronium huge rotors. This kicks out roughly 77M EU/t. The XL steam turbine consuming the output steam would give me (IIRC, not in-game rn to validate) less than 1A UV to add to this. It's just not worth it.

Just my $0.02, interested to hear the discussion on this :-)

**Comment by IkarusFalling** [comment]
The Multi would be useful when using Steam Producing Multis when not desiring to place or use Turbines for example when producing Panahoe Lava as currently there is no way to make that without producing Steam and using Distilled (Thermal Boiler still bugged atleast in stable) so if it is sensible to waste the steam but recovery is desired the multi would proof useful

**Comment by fluffle** [comment]
Can I assume the conversation about this (and possibly the related rebalancing of SC steam numbers for plasmas after the Great Tin Nerf) is happening on Discord, and I should just wait patiently?

**Comment by wlhlm** [comment]
As far as I can see, there was no further discussion of this Coolant Tower topic outside of Github.

**Comment by fluffle** [comment]
@Steelux8 any chance you could take another look at this too? At the moment I need the cooling tower to condense 40,960M L of steam every 5s (a.k.a. 10 UHV input hatches) to meet the demands of an XL SC steam turbine with 16 standard-sized infinity turbines. I have no interest in shelling out another 576 infinity pre-DTPF for rotors, or another chunk's worth of space in my smelting 3x3, to support a steam turbine mostly for condensing.

Perhaps the cooling tower is too convenient for your current balancing desires, but the likely alternative I'd end up taking in the absence of it is to have the space elevator generate me approximately-free distilled water as opposed to closing the loop, at this point.

**Comment by Steelux8** [comment]
I understand that the second XL turbine is too expensive for the tiny amount of EU/t it will produce compared to the SC XL. However, having this coolant tower able to replace the XL would simply remove the intended cost of looping the distilled water, would it not? The SC turbine, just like the SH turbine, doesn't output water directly for a reason: the complete setup is supposed to have a second turbine in front of the first.

One other thing I'd like to ask is: why is a SH steam setup expected to have 2 turbines, but an SC setup only 1 with this change? Again, I know that the second turbine's output is minimal on the SC case, but I don't think that's reason enough to let the coolant tower replace it.

**Comment by xSkewer** [comment]
> I understand that the second XL turbine is too expensive for the tiny amount of EU/t it will produce compared to the SC XL. However, having this coolant tower able to replace the XL would simply remove the intended cost of looping the distilled water, would it not? The SC turbine, just like the SH turbine, doesn't output water directly for a reason: the complete setup is supposed to have a second turbine in front of the first.

The coolant tower is the intended method for looping steam for SC steam according to the dev who added both.

**Comment by Steelux8** [comment]
> The coolant tower is the intended method for looping steam for SC steam according to the dev who added both.

Ah, I never heard about that. Do you remember where you saw this? I'll approve in that case.

**Comment by xSkewer** [comment]
https://discord.com/channels/181078474394566657/603348502637969419/992398653597679646 Not sure if this is enough evidence, but this is what I was going off of. I'm not sure what purpose the coolant tower would have otherwise.

**Review by Steelux8 — APPROVED** [review]

**Comment by fluffle** [comment]
Thanks for the approval!

> However, having this coolant tower able to replace the XL would simply remove the intended cost of looping the distilled water, would it not?

<opinions follow, do with them what you will>

This is a valid question, because on the face of it the answer is obviously "yes". But when not looping is a valid alternative, because dangote distilling water (or just pumping it from SPACE) is viable,  the intended cost becomes somewhat moot. The primary cost of a loop via an XL steam turbine, at least to me, is the rotor cost (pre-DTPF infinity) and the additional time/effort to build it and integrate it with my power generation control systems. The incentive to do that is a relatively small uptick in EU/t generation -- it's just not enough to be worth it.

I think the balance question of using an XL steam turbine to close the loop is thrown off by SC steam being 100x more energy dense than steam. In GT power terms that's a little over 3 tiers of power different, or e.g. IV -> UV; by the time you're generating a reasonable amount of UV power you don't even think about IV power needs any more. By comparison, SH steam is only 2x more dense than normal steam, and you get the appropriate turbines at the next power tier. At this point the prospect of 50% more power *and* a closed loop for your distilled water is something most players would find hard to turn down.

But if you ask a player generating 50A of UHV power with SC steam whether 1A of UV power offsets the additional player time, control system complexity and resource requirements associated with closing the loop via an XL steam turbine, I expect the answer will mostly be "nooope". That's certainly where I am at least. This coolant tower multi is a nice-looking alternative that trades off the negligible energy gains for a simpler control loop and no rotor upkeep cost. I can see why the person who wrote this mod created it.

IMO (and this may be inviting nerfs I later regret) an interesting way to balance this multi might be to limit its throughput. At the moment it processes as much steam as you can feed it every 5 (soon to be 1) seconds. If it was limited to only allow 1 input hatch that would change the incentives and the value proposition -- you can only cool as much steam per second as the largest input hatch tier you're capable of creating.

For me that's UHV (i am regretting 2.3.4 and the tengam migration) which means for my current turbine setup I would need to build a second coolant tower to cool the 8192 buckets/s of steam I am producing.

**Comment by Steelux8** [comment]
What you explained there is why I think the SC steam mechanic is undesirable to work with for me. The reason it was invented was to reduce flow of the steam fluid by making it a denser one, but it multiplies plasma powergen values just by adding an EHE and this turbine after it. Any turbines that would follow aren't even encouraged because of how SC allows next to no power generation on the next steps.

That said, coolant tower it is.

**Comment by fluffle** [comment]
The way I would phrase the criticism, I think, is that a static 3x energy output multiplier for building a couple of additional, relatively cheap multis is too strong a buff to ignore. This has been addressed in other parts of the pack with multi tiering allowing variable multipliers, so imma suggest similar things here.

With the understanding that these are significantly more invasive changes, of course...

The 3x multiplier happens in the extreme HX, and I think that is the multi most amenable to tiering. It uses pipe blocks of which multiple tiers already exist, so we could set things up such that better pipe materials produce better "heat transfer" (SC steam output multipliers) for plasmas. Furthermore we could require that some higher-tier plasmas needed the higher tier pipes or they would "melt" (explode) the HX -- thus forcing people to commit expensive resources for greater power output. It could even be asserted that the default tungstensteel pipes are completely unsuitable for use with plasmas.

That's a lot more code than this, though ;-)

**Pull request merged**
