### PR TITLE
change PotassiumNitrate to Salpeter

### PR DESCRIPTION
**Pull request by Dream-Master**
KNO3 =  KNO3

(cherry picked from commit e4e904dc876229eb8174fce4bc33900f02bc8e66)

### CODE REVIEW

**Comment by GlodBlock** [comment]
but they have differnent oredict ingame, so they are different items

**Comment by Dream-Master** [comment]
yes but they are the same item chemstry wise so not sure why we add it in the first place. I change al recipes and let the material in for compatibility reasons. Maybe we set id to -1 some day. (Gt code)

**Comment by Steelux8** [comment]
Saltpeter is supposed to be an "ore", while potassium nitrate is a pure chemical compount. Saltpeter could have impurities, but that isn't used at all in the recipes so it's a good idea to merge them together.

**Review by Steelux8 — APPROVED** [review]

**Comment by Dream-Master** [comment]
So far i understand Glod right I need to work on this pr. He said I can remove this recipes because the saltpeter recipes already in the code. Need to check later.

**Pull request merged**
