### PR TITLE
Might fix wrong dust from macerating raw ore

### PR DESCRIPTION
**Pull request by Ethryan**
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16332

Part of fixing: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15984

image
Seems to be working.

### CODE REVIEW

**Comment by hallucinogender** [comment]
Since I wrote the issue that prompted this, I've discovered quite a few other instances of this. Naquadah, naquadah-related things, and anything which gives samarium ore concentrate (if I recall correctly; whichever one is the samarium one) all have a similar problem. I think I recall seeing something like it mentioned with platline too but that having been fixed, so presumably it's the same issue.

**Comment by Ethryan** [comment]
Ok, So there were stuff in Lanthanides I had to fix. This only fixes the Naquadah stuff.

**Comment by chochem** [comment]
> Since I wrote the issue that prompted this, I've discovered quite a few other instances of this. Naquadah, naquadah-related things, and anything which gives samarium ore concentrate (if I recall correctly; whichever one is the samarium one) all have a similar problem. I think I recall seeing something like it mentioned with platline too but that having been fixed, so presumably it's the same issue.

the ticket is a month old, eth just falsely closed it earlier :P

**Comment by Ethryan** [comment]
This and the Lanth pull should fix the wrong output @chochem .

**Review by chochem — APPROVED** [review]

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
