### PR TITLE
Fixes Large Essentia Smeltery autoplace in survival

### PR DESCRIPTION
**Pull request by Lyfts**
Don't know how this was missed, but i can no longer reproduce.

Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13983

### CODE REVIEW

**Comment by Alastors** [comment]
Lmfaoooooooo, first off, mood. Second off, I hate that I have to ask this, but you have tested this in a world yourself and ensured it did?

**Comment by Alastors** [comment]
@Lyfts  ^

**Comment by Lyfts** [comment]
Of course I have, want a screenshot of the test world?

**Comment by Lyfts** [comment]
If something is off on your side, a description of it would be a tad more helpful.

**Comment by Alastors** [comment]
Nah it's nothing like that just too many instances of people not testing their changes

**Comment by Lyfts** [comment]
Sorry man, just saw what you said on discord straight after. I misunderstood what you meant :)

**Review by Alastors — APPROVED** [review]

**Pull request merged**
