### PR TITLE
preciousMetalAlloy-addMetaSolidifierRecipes

### PR DESCRIPTION
**Pull request by lc-1337**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@lordIcocain can you make a pic of the recipe that is autogenerated?

**Comment by lordIcocain** [comment]
6 new recipe 
image
image
image
image

**Comment by Dream-Master** [comment]
and now you make them all in the extruder ? at mv too ?
What are the ebf or abs recipe. Is the fluid a shortcut ?

**Comment by lordIcocain** [comment]
Extruder mostly using hv
image

ABS recipe
image

EBF recipe with xenon, freezer cooling at mv
image

**Comment by Dream-Master** [comment]
so the freez process is the real short cut. That cooling is at mv is a old behaviour i change that for gt stuff but not for gt++

**Comment by Dream-Master** [comment]
lets go over it after 2.6.0

**Review by Dream-Master — CHANGES_REQUESTED** [review]
This is a shortcut to avoid EBF and Vac Freezer.

**Comment by eigenraven** [comment]
Closing due to merging this addon with gt5u, if we want to discuss this PR again it's a one line change to copy over.

**Pull request closed without merging**
