### PR TITLE
[RFC] Efficiency cut off on UCE

### PR DESCRIPTION
**Pull request by 0lafe**
Adds a max to the thoughput of the UCE, scaling with the efficiency coefficient of the fuel

### CODE REVIEW

**Comment by Steelux8** [comment]
Can you explain why you chose this formula? Also, what does an optimal setup look like here, how much fuel can be used with this change without taking a big efficiency loss?

**Comment by 0lafe** [comment]
I just picked a simple option for lowering efficiency with increased throughput, eventually capping it. It depends on the fuel for how much this impacts it. It's not very complex, it just makes 1/2 of the value of 5 divided by the efficiency coefficient the optimal throughput of fuel. Diesel has a coefficient of 0.02, so 5/0.02 gives 250, making 125L/t of fuel the highest output of power you can get. 

Gas caps at 500L/t and rockets at 1000L/t. These max values have their current efficiency (related to Fuel : Promoter) multiplied by 1/2. So max throughput only has 75% efficiency at most, but most likely worse than that. 

This could probably be adjusted a lot better to look more like the LRE's dropoff, but Im not that skilled with efficiency curves. Do you have any improved ideas? Imo this one caps well, but doesn't benefit lower throughputs enough.

**Comment by Steelux8** [comment]
You should not make this second calculation depend on the coefficient used for the original formula. If it ends up being changed for a reason regarding the combustion promoter, for example, this part of the calculation will also be changed for no reason.

The graph you showed me looked nice, but for me, capping the effective throughput of a multi with a function needs to be made more clear with more graphs. What would be the efficiency of the fuel in the multi, from 0 input all the way to the amount that outputs the most EU, and until it falls back to 0?

**Comment by 0lafe** [comment]
I can refactor this to not depend on current values. However do the proposed limits seem fair? (500L/t diesel, 1000 gas and 2000 rocket?)

>What would be the efficiency of the fuel in the multi, from 0 input all the way to the amount that outputs the most EU, and until it falls back to 0?

Theres still the efficiency provided by the promoter. That is then multiplied by a linearly decreasing fraction represented by (a - L/t) / a where a is ~250 for diesel, 500 for gas and 1000 for rockets. L/t = a/2 gives the max output the machine could make, as anything more than that looses more energy on efficiency than the increased throughput provides. So a/4 and 3a/4 throughputs give the same power output, but one uses a lot more fuel. This means overshooting that value of a/2 is going to hurt your production a LOT. as the function is linear, a throughput of a/4 will give 75% efficiency, a/2 gives 50%, a/3 gives 66% etc

**Comment by Steelux8** [comment]
> I can refactor this to not depend on current values. However do the proposed limits seem fair? (250L/t diesel, 500L/t gas and 1000L/t rocket?)

I believe it should be the same for all fuels. All of them should have the same "maximum" throughput, and just differ based on their fuel values and, in turn, the processing chains involved.

> Theres still the efficiency provided by the promoter. That is then multiplied by a linearly decreasing fraction represented by (a - L/t) / a where a is ~250 for diesel, 500 for gas and 1000 for rockets. When L/t = a/2 the machine outputs the most power but only has an efficiency of 50%. So a/4 and 3a/4 throughputs give the same power output, but one uses a lot more fuel. This means overshooting that value of a/2 is going to hurt your production a LOT. as the function is linear, a throughput of a/4 will give 75% efficiency, a/2 gives 50%, a/3 gives 66% etc

I like that there's a curve, but the maximum throughput ending up at 50% efficiency is far too low to be reasonable. I don't know what formula would enable this, but I think it would be much better if efficiency was distributed in this fashion (with 100% efficiency being the value from the first formula without changes):

a/8 - 100% (all values smaller than this are also 100%, the multi can take small amounts just fine)
a/4 - 90%
a/2 - 80% (the maximum throughput)
a - 50% (fuel generation does not equal 0 with double the previous amount, is the fuel just being voided here?)
2a - 25% (the EU/t would end up at a plateau despite the input amount increase, but the EU/t would never go down, only the efficiency)

**Comment by bombcar** [comment]
I personally the idea of being able to push beyond the resonance limits - with corresponding loss of efficiency and maybe even horrible noises and increased maintenance costs

**Comment by Glease** [comment]
Isn't UCE supposed to be capped by dynamos? Do you even know what you are changing?

**Comment by GlodBlock** [comment]
the curve looks completely broken now, you even can get negative effencent.
image

**Comment by Steelux8** [comment]
image

image

You would do better with a function like this. X-axis is L/t fuel input, Y-axis is percentage of efficiency, and it multiplies with the original function. Its maximum should be 100, so make it go down to 100 in the code if it is above this number.

In summary, the maximum of 100% means it'll give the result of the original function, untouched, providing no penalty to efficiency up to 100L/t, with 200L/t running at around 74%. If the maximum amount of input at 100% efficiency is too low, just change the coefficient, and make it independent from the one used in the original function.

**Comment by Dream-Master** [comment]
0lafe — Yesterday at 7:25 PM
Not at the moment you can close it. I don't think anyone wanted the change
sorry

**Pull request closed without merging**
