### PR TITLE
thorium balance change

### PR DESCRIPTION
**Pull request by GlodBlock**
- liquid thorium fuel is for breeding th232 effectively now. it won't output lutetium.
 - th232 lcr line is consume more florine now
 - liquid thorium fuel is more easy to make
 - HDP rods output argon instead of krypton

### CODE REVIEW

**Comment by kuba6000** [comment]
> so the main goal here is to nerf lutetium or is there some other alternative recipe planned?

https://github.com/GTNewHorizons/bartworks/pull/193

**Review by kuba6000 — APPROVED** [review]
So the calcium stays neutral ?

**Comment by GlodBlock** [comment]
yep calcium stays neutral

**Comment by kuba6000** [comment]
> yep calcium stays neutral

Ok, then good to merge I think

**Review by chochem — CHANGES_REQUESTED** [review]
I dont think this should be merged until there is an alternative for lutetium in place. In particular if this makes it into stable but the alternative doesnt. ic2 nuke spam shouldnt be the goal.

**Comment by Pxx500** [comment]
> I dont think this should be merged until there is an alternative for lutetium in place. In particular if this makes it into stable but the alternative doesnt. ic2 nuke spam shouldnt be the goal.

This will be merged along HTGR buffs and changes

**Comment by kuba6000** [comment]
> > I dont think this should be merged until there is an alternative for lutetium in place. In particular if this makes it into stable but the alternative doesnt. ic2 nuke spam shouldnt be the goal.
> 
> This will be merged along HTGR buffs and changes

I have finished HTGR buff, https://github.com/GTNewHorizons/bartworks/pull/193
This is now how you make lutetium.

**Review by Steelux8 — CHANGES_REQUESTED** [review]
HTGR rework to make it better before next stable is fine, but not nerfing existing useful lines. Anyone who has been using this to stock up on lutetium will be forced to go back to IC2 nukes or make the HTGR all of a sudden. Wait until next stable to get this nerf through.

**Comment by Dream-Master** [comment]
@chochem @Steelux8 bartworks pr is done by Kuba <https://github.com/GTNewHorizons/bartworks/pull/193> can we merge this now?

**Comment by Steelux8** [comment]
This is a removal of an existing and useful lutetium line. Whether or not it will be removed is to be decided after the next stable, not before it.

**Comment by Dream-Master** [comment]
> This is a removal of an existing and useful lutetium line. Whether or not it will be removed is to be decided after the next stable, not before it.

ok fine lets do that after next stable

**Comment by Dream-Master** [comment]
After the release i make it ready for review

**Pull request merged**
