### PR TITLE
More CoAl fixes

### PR DESCRIPTION
**Pull request by Phineasor**
…n from MadMan, will allow for faster automation to help prevent spamming them.

Just allows for 2 more input buses, good for automation.
Got permission from MadMan, tested in dev instance, multi formed with new buses and without, no problems.

### CODE REVIEW

**Comment by Phineasor** [comment]
oh, madman when your here it might be wise to also in this PR, change the laser hatch locations, although that's up to you.

**Comment by minecraft7771** [comment]
We build ours vertical to save space and keep it in a chunk. It would be very cool if you could also allow an energy hatch on the lowest position. Currently this makes using lasers not really possible unless you route an AT around it or build it upside down

Allowing the block below where we have the energy hatch now would already be sufficient.

**Comment by LewisSaber** [comment]
> We build ours vertical to save space and keep it in a chunk. It would be very cool if you could also allow an energy hatch on the lowest position. Currently this makes using lasers not really possible unless you route an AT around it or build it upside down  Allowing the block below where we have the energy hatch now would already be sufficient.

image
you can build it inside

**Comment by minecraft7771** [comment]
Ye thats what I meant with "unless you route an AT around it". It needs an extra AT which is unncessary imo. I can't think of another machine that needs this extra treatment, which also makes it a bit uglier imo.

**Comment by Phineasor** [comment]
> Ye thats what I meant with "unless you route an AT around it". It needs an extra AT which is unncessary imo. I can't think of another machine that needs this extra treatment, which also makes it a bit uglier imo.

This is what I meant by moving the energy hatches, the last layer is where I want it as well.

**Comment by Phineasor** [comment]
I added 4 more slots for energy hatches, it was everyone's demand.

**Review by MadMan310 — APPROVED** [review]

**Pull request merged**
